### ISSUE TITLE
Contains query for Edge search is inconsistent

### ISSUE THREAD

**Issue by wshayes** [biodati/support#8]
> starting with p(HGNC:STAT4), I am expecting to see act(p(HGNC:STAT4)) and others

**Link:** [Conversation with User](https://app.intercom.com/a/apps/q01vyayo/respond/inbox/all/conversations/18849326414)

**Customer:** [User](https://app.intercom.com/a/apps/q01vyayo/users/5b26f316e3bd786134b8c0e2/all-conversations) from [Brisbane](https://app.intercom.com/a/apps/q01vyayo/companies/5ba8e29df3c462cf5183b967)
**Company ID:** 5ba8e29df3c462cf5183b966-qualification-company
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/q01vyayo/respond/inbox/all/conversations/18849326414) when this issue is closed.

**Comment by adifabio** [comment]
is this still the case?
